[project]
name = "webdjango"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.7",
    "gunicorn==23.0.0",
    "psycopg>=3.2.10",
    "psycopg2-binary>=2.9.10",
]
